title: Just the Docs Sample
description: This is a test project. 
theme: just-the-docs

url: https://kalarp.github.io/jtdsample

aux_links:
  Template Repository: https://github.com/kalarp/just-the-docs-sample
